language: node_js
node_js:
  - "8.16"
before_deploy: 'echo "DEPLOYMENT STARTED... âŒšâŒ›âŒš"'
script:
  - npm run dist
  - npm run build-demo-js
deploy:
  - provider: npm
    on:
      tags: true
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    run: 'echo "ğŸ†• NPM DEPLOYMENT IS FINISHEDâœ¨âœ”ğŸš€"'
  
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    local_dir: ./examples/js/dist
    on:
      tags: true
    run: 'echo "ğŸ± GITHUB PAGES DEPLOYMENT IS FINISHEDâœ¨âœ”ğŸš€"'
after_deploy: 'echo "All done ğŸ‘ğŸ‘ğŸ‘ğŸ‘ğŸ‘ğŸ‘ğŸ‘ğŸ‘ğŸ‘ğŸ‘"'