language: node_js
node_js:
  - "8.16"
before_deploy: "echo 'DEPLOYMENT STARTED... âŒšâŒ›âŒš'"
script:
  - npm run dist
  - npm run build-demo-js
deploy:
  - provider: npm
    on:
      tags: true
    cleanup: false
    email: $NPM_EMAIL
    api_token: $NPM_TOKEN
    run: "echo 'ğŸ†• NPM DEPLOYMENT IS FINISHED.âœ¨âœ”ğŸš€'"
    edge: true
  
  - provider: pages
    on:
      tags: true
    cleanup: false
    token: $GITHUB_TOKEN
    keep_history: true
    allow_empty_commit: true
    local_dir: "./examples/js/dist"
    run: "echo 'ğŸ± GITHUB PAGES DEPLOYMENT IS FINISHED.âœ¨âœ”ğŸš€'"
    edge: true
after_deploy: "echo 'All done ğŸ‘ğŸ‘ğŸ‘ğŸ‘ğŸ‘ğŸ‘ğŸ‘ğŸ‘ğŸ‘ğŸ‘'"
